# Generated by Django 3.2.25 on 2024-06-18 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Nurse', 'Nurse'), ('Receptionist', 'Receptionist'), ('Doctor', 'Doctor'), ('Specialist', 'Specialist')], max_length=20)),
                ('department', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Endocrinology', 'Endocrinology'), ('General Medicine', 'General Medicine')], max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_hire', models.DateField()),
                ('shift_timings', models.CharField(max_length=50)),
                ('qualifications', models.TextField()),
                ('years_of_experience', models.PositiveIntegerField()),
                ('specializations', models.TextField()),
                ('supervisor_id', models.CharField(blank=True, max_length=10, null=True)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('languages_spoken', models.CharField(max_length=100)),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('office_location', models.CharField(max_length=100)),
                ('access_level', models.CharField(max_length=20)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('certifications_and_licenses', models.TextField(blank=True, null=True)),
                ('training_records', models.TextField(blank=True, null=True)),
                ('medical_clearances', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('medical_history', models.TextField()),
                ('current_treatment', models.TextField()),
                ('emergency_contact', models.CharField(max_length=100)),
                ('assigned_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.medicalstaff')),
            ],
        ),
    ]
